# Generated by Django 3.2 on 2023-03-03 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menuu',
            new_name='Menu',
        ),
    ]
