# Generated by Django 3.2 on 2023-03-03 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_rename_menuu_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='menu_id',
            new_name='parent_menu',
        ),
    ]
