# Generated by Django 3.2 on 2023-03-06 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_auto_20230305_0301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='explicit_url',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='level',
        ),
    ]
